"""User email is not nullable

Revision ID: 169e8d71f0fa
Revises: 30ce576f4e53
Create Date: 2025-02-04 08:46:32.514969

"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '169e8d71f0fa'
down_revision: str | None = '30ce576f4e53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'email',
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'email',
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
